### ISSUE TITLE
Restarting ARC job adds extra entries to initiated_jobs.csv

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/ARC#105]
When restarting an ARC job, I noticed that the job numbers would jump up by a lot. It seems like when job objects are recreated for currently running jobs, it writes those jobs to the `initiated_jobs.csv` file. Then, since the job number is determined by counting lines in the file, the next new job gets a much higher number.

I think the desired behavior would be not logging these jobs to `initiated_jobs.csv`, which should resolve the job numbering automatically.

**Comment by alongd** [comment]
Strange. When we load jobs we pass the restart dictionary to Scheduler in ARC.execute().
There, under `restore_running_jobs()` we create a `job` object, passing `job_num` to the object. We set the job number (saving in the .csv file) only if `job_num` doesn't already exist. I couldn't see just by looking at it why it would behave like that, but I can look into it.

**Comment by mliu49** [comment]
It seems that `_write_initiated_job_to_csv_file` is called at the end of `Job.__init__` regardless of whether or not `job_num` was provided.

**Comment by alongd** [comment]
You're right, I'll fix it. Thanks!

**Comment by alongd** [comment]
Should be solved by https://github.com/ReactionMechanismGenerator/ARC/pull/104
@mliu49, let me know if you still have this issue
