### ISSUE TITLE
Rotor detection fails in some special cases

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/ARC#171]
Rotor detector fails in some special cases
(1) When one end of the dihedral has triple bonds, e.g., H-C#C-O-H. It will take C#C-O-H as a rotor.
(2) From the original structure, it seems existing rotors. But when looking at other resonance structures, then some of the rotors are fake, e.g., O=[C]C=O. It looks like O=[C]-C=O is a rotor, but it has a resonance structure: O=C=C-[O], which indicates that it is not really a rotor (The actual angle O-C-C is 180 degree in the optimized structure).

Suggestion:
These two cases fail when they have bond angle = 180. We can check triple bond or resonance structure, but there may be other cases impossible to identify beforehand. So we can check `if any bond angle == 180` in the dihedral about to be scanned, if so, ignore the rotor.

**Comment by alongd** [comment]
See `check_special_non_rotor_cases` [here](https://github.com/ReactionMechanismGenerator/ARC/blob/master/arc/species/conformers.py#L1290)
Perhaps you can come up with suggestions for improvement.
Note that we don't really check the angle, since the unoptimized 3D structure has wrong angles

**Comment by xiaoruiDong** [comment]
Thanks for letting me know the function. What I mean is actually check the angle before submitting the scan job. As we only submit scan job after optimization, at that time we should have an accurate bond angle:
Start ARC -> find rotors -> conformers -> opt -> check the angle -> scan

**Comment by alongd** [comment]
Rotors are determined before running opt. We could reconsider that if we want. More importantly, see why check_special_non_rotor_cases doesn't address the original issue and whether it could be updated?

Regarding the resonance case, I think it's OK to declare that bond as a potential rotor (the resonance might be weak), worst case we'll find a hight barrier and invalidate the rotor.

**Comment by alongd** [comment]
@xiaoruiDong, what's the status of this issue?

**Comment by xiaoruiDong** [comment]
This issue relates to a special kind of molecules: species have a triple bond but the bond angle is not 180 degrees. All the cases I found relates to the open-shell species (something like [C]#CC). ARC will calculate the rotor scan. And some of them do have a slightly large barrier (larger than the free rotor threshold we use). The thing is this kind of rotor scans have a high chance of failure, and the failures happen in a similar pattern: the bond angle of triple bonds change to 180 degrees and the gaussian job crashed. I haven't figured out a solution to this yet.

**Comment by whgreen** [comment]
I think this is a situation where rotor and large amplitude bend are strongly coupled, need to treat them as coupled.
To get V(phi,theta) should scan them both as a mesh, optimizing the 3N-8 remaining internal coords while keeping both phi and theta locked. Similar to cases where umbrella is coupled to a dihedral, or two rotors are coupled.

Bill

Sent from my phone.

On Oct 3, 2019, at 10:01 AM, Xiaorui Dong <notifications@github.com<mailto:notifications@github.com>> wrote:


This issue relates to a special kind of molecules: species have a triple bond but the bond angle is not 180 degrees. All the cases I found relates to the open-shell species (something like [C]#CC). ARC will calculate the rotor scan. And some of them do have a slightly large barrier (larger than the free rotor threshold we use). The thing is this kind of rotor scans have a high chance of failure, and the failures happen in a similar pattern: the bond angle of triple bonds change to 180 degrees and the gaussian job crashed. I haven't figured out a solution to this yet.
