### ISSUE TITLE
ImportError: No module named quantities

### ISSUE THREAD

**Issue by NtuCheRoy** [ReactionMechanismGenerator/ARC#193]
I solved #189 problem by update ARC after #191. And it appear new import error. Below is the trace  message.
![image](https://user-images.githubusercontent.com/53944308/64917255-bf055080-d7c0-11e9-907a-f117ec296b70.png)

**Comment by NtuCheRoy** [comment]
I solves this problem by `git clone https://github.com/python-quantities/python-quantities.git` and add this file to PYTHONPATH.

**Comment by alongd** [comment]
This usually occurs when running ARC without activating the environment (`activate arc_env`). The quantities module happens to (usually) be the first thing it complaints about. Activating the environment should solve this and allow smooth executing (no need to install anything).

**Comment by dpfnmt** [comment]
Where is the path you added
