### ISSUE TITLE
ImportError: cannot import name ATOMTYPES

### ISSUE THREAD

**Issue by jeehyunatrmg** [ReactionMechanismGenerator/ARC#235]
I prepared an ARC input and try to run on arc_env.

I got an error saying

ImportError: cannot import name ATOMTYPES

**Comment by alongd** [comment]
Could you confirm that both ARC and RMG-Py are up to date?
(type `git log` to see the most recent commit date)
Also, after updating RMG-Py, make sure it is compiled (`make clean`; `make`)
