### ISSUE TITLE
Job type '1d_rotors' is not supported

### ISSUE THREAD

**Issue by jeehyunatrmg** [ReactionMechanismGenerator/ARC#238]
I recently installed ARC in rmg server and try to run ARC. (I checked that 'make test' worked fine).

When I ran ARC in rmg server using slurm, I got following errors as below.

File "/home/jeehyun/ARC/arc/common.py", line 460, in initialize_job_types
    raise InputError(f"Job type '{job_type}' is not supported. Check the job types dictionary "
arc.exceptions.InputError: Job type '1d_rotors' is not supported. Check the job types dictionary (either in ARC's input or in default_job_types under settings).

**Comment by alongd** [comment]
Try replacing `1d_rotors` with `rotors` in your job dictionary (either the job_types argument in your input file or in your settings.py)

**Comment by jeehyunatrmg** [comment]
Hi Along! It worked after I replaced 1d_rotors in my input! Thanks!! 

However, this time, I got an error message different. I will put it on the other issue!
