### ISSUE TITLE
FileNotFoundError: Could not find SSH key for the server ARC is running on

### ISSUE THREAD

**Issue by jeehyunatrmg** [ReactionMechanismGenerator/ARC#239]
It looks like, arc cannot find the key... I am trying to submit job using slurm inside RMG server

For some reason, arc cannot find it.

Below is the settings in settings.py in ~/ARC/arc. I also finished copy rsa keys in both servers.

```python
servers = {
    'pharos': {
        'cluster_soft': 'OGE',
        'address': 'pharos.mit.edu',
        'un': 'jeehyun',
        'key': '~/jeehyun/.ssh/id_rsa',
    },
    'rmg': {
        'cluster_soft': 'Slurm',
        'address': 'rmg.mit.edu',
        'un': 'jeehyun',
        'key': '~/jeehyun/.ssh/id_rsa',
    },
}

# List here servers you'd like to associate with specific ESS.
# An ordered list of servers indicates priority
# Keeping this dictionary empty will cause ARC to scan for software on the servers defined above
global_ess_settings = {
    'gaussian': ['rmg', 'pharos'],
    'molpro': 'rmg',
    'qchem': 'pharos',
    'onedmin': 'pharos',
}
```

**Comment by alongd** [comment]
If you run ARC on a server, you should define that server as `local` in your servers settings. For example, if you run on the RMG server, you should set:

```python
servers = {
    'pharos': {
        'cluster_soft': 'OGE',
        'address': 'pharos.mit.edu',
        'un': 'jeehyun',
        'key': '~/jeehyun/.ssh/id_rsa',
    },
    'local': {
        'cluster_soft': 'Slurm',
        'un': 'jeehyun',
    },
}
```

Notice that the server you run on is defined with the reserved name `local` (not `rmg`). Read more about server definitions [here](https://reactionmechanismgenerator.github.io/ARC/installation.html#generate-rsa-ssh-keys-and-define-servers).
