### ISSUE TITLE
Arc is creating two sets of calculation in input file

### ISSUE THREAD

**Issue by jeehyunatrmg** [ReactionMechanismGenerator/ARC#241]
When Arc was running single point energy calculation, it created input files as below.

```
***,name
memory,224,m;
geometry={angstrom;
I       0.00000000    0.00000000    0.00000000
}

**basis=cc-pVDZ
int;
{hf;wf,spin=1,charge=0;}
uccsd(t);**

basis=6-311g**
int;
{hf;
maxit,1000;
wf,spin=1,charge=0;}

uccsd(t);


---;
```
Since I set ccsd(T)-6-311g**, I can understand the bottom lines. However, I cannot figure out how cc-pVDZ came out

**Comment by alongd** [comment]
Also strange it has `**` before and after the second block

**Comment by alongd** [comment]
Can you upload your input file?

**Comment by jeehyunatrmg** [comment]
allow_nonisomorphic_2d: true

opt_level: B3LYP/6-311G**
freq_level: B3LYP/6-311G**
freq_scale_factor: 0.967 
sp_level: ccsd(t)/6-311G**
scan_level: B3LYP/6-311G**

job_types: {rotors: true, conformers: false, fine: true, freq: true, onedmin: false,
  opt: true, orbitals: false, sp: true}


project: I_atom_interference-103019

species:

  - label: N2-2
    multiplicity: 2 
    smiles: '[CH]=CC1=CC=C2C=CC=CC2=C1'

  - label: ETN-2
    multiplicity: 1
    smiles: 'C#CC1=CC=C2C=CC=CC2=C1'

  - label: I
    multiplicity: 2 
    smiles: '[I]'

  - label: C12H9I
    multiplicity: 1
    smiles: 'IC=CC1=CC2=C(C=CC=C2)C=C1'

  - label: HI
    multiplicity: 1 
    smiles: 'I'

**Comment by alongd** [comment]
I identified two problems here.
The minor problem is that molpro does not accept the `6-311G**` notation (it should recognize the equivalent `6-311G(d,p)` notation, though)
The more important problem is that the Gaussian output files complain that this basis set does not support Iodine, although from reading online I think they should.
Anyway, I would recommend selecting a better model chemistry for this system (search for basis sets for your chemistry [here](https://www.basissetexchange.org/)). This is outside the scope of ARC, but I would recommend not using B3LYP for freq/opt, and using a better basis set in molpro.
The original problem you reported is indeed a bug with one of ARC's troubleshooting methods. I'll make a fix for it.

**Comment by jeehyunatrmg** [comment]
Dear Alon,

That is awesome!

I also found out that 6-311G** is too heavy for calculation including I atom. Duminda recommended me basis set freezing cores and make the calculation cheaper. (FYI, def2-TZVP)

Always many thanks for your kindness and helps!

Sincerely,
Jeehyun Yang


Jeehyun Yang
Ph.D. Candidate

Department of Earth, Atmospheric and Planetary Sciences
Massachusetts Institute of Technology

E18-509

77 Massachusetts Avenue

Cambridge, MA 02139
jeehyun@mit.edu<mailto:isobill@mit.edu><mailto:isobill@mit.edu>

________________________________

**Comment by alongd** [comment]
@jeehyunatrmg, my pleasure. If you plan on getting rates/thermo, though, you should use [a model chemistry supported by Arkane](http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#model-chemistry), which might complicate things for this system until we expand the supported model chemistries.
