### ISSUE TITLE
Error in converting xyz to 2D molecule leads to false isomorphism check failure 

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/ARC#299]
**Describe the bug**
I am trying to use ARC for a slightly unconventional species, chloromethylene, which has a smiles of [CH]CCl. Below are the xyz coordinates optimized at wb97m-v/def2-tzvpd

```
C	1.1709385492000002	0.17631434110000002	-0.0
Cl	-0.5031634975000001	-0.010943003600000003	0.0
H	1.5281481620000001	-0.8718549847000001	0.0
```

Looking at this geometry in Avogadro, this appears to be the right geometry for this molecule. However, when I try to create an ARC species, I get the following errors:

```
ERROR:root:Could not update atomtypes for this molecule:
multiplicity -187
1 C  u0 p0 c0 {2,T} {3,S}
2 Cl u0 p2 c0 {1,T}
3 H  u0 p0 c0 {1,S}

ERROR:root:Could not update atomtypes for this molecule:
1 C  u0 p0 c0 {2,T} {3,S}
2 Cl u0 p2 c0 {1,T}
3 H  u0 p0 c0 {1,S}

ERROR:root:Could not update atomtypes for this molecule:
1 C  u0 p0 c0 {2,T} {3,S}
2 Cl u0 p2 c0 {1,T}
3 H  u0 p0 c0 {1,S}

WARNING:arc:XYZ and the 2D graph representation for spcs54 are not isomorphic.
Got xyz:
{'symbols': ('C', 'Cl', 'H'), 'isotopes': (12, 35, 1), 'coords': ((1.1709385492000002, 0.17631434110000002, -0.0), (-0.5031634975000001, -0.010943003600000003, 0.0), (1.5281481620000001, -0.8718549847000001, 0.0))}

which corresponds to C#Cl
1 Cl u0 p2 c0 {2,T}
2 C  u0 p0 c0 {1,T} {3,S}
3 H  u0 p0 c0 {2,S}


and: [CH]Cl
multiplicity 3
1 Cl u0 p3 c0 {2,S}
2 C  u2 p0 c0 {1,S} {3,S}
3 H  u0 p0 c0 {2,S}

WARNING:arc:Element order in xyz (('C', 'Cl', 'H')) differs from mol (['Cl', 'C', 'H'])
```

To be clear, this is likely an error with RDKit/Openbabel, but I am curious how we should handle this inside of ARC. For example, here ARC can probably work out the correct connectivity, just not the correct bond orders. **Should we change ARC to fall back to a warning if the isomorphism fails but the connectivity seems right?**

**How to reproduce**
Try executing the following:

```
ARCSpecies(smiles='[CH]CCl',  xyz='C\t1.1709385492000002\t0.17631434110000002\t-0.0\nCl\t-0.5031634975000001\t-0.010943003600000003\t0.0\nH\t1.5281481620000001\t-0.8718549847000001\t0.0\n')
```

**Expected behavior**
ARC should let this pass with at most a warning

**Comment by alongd** [comment]
@amarkpayne, should be fixed now, I added `[CH]Cl` to the tests

**Comment by amarkpayne** [comment]
Thanks for the fix, @alongd !
