### ISSUE TITLE
Add option to only perform a fine optimization

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/ARC#303]
**Is your feature request related to a problem? Please describe.**
Usually, when one uses ARC, they need ARC to start from the very beginning and generate a plausible conformer for the molecule, and then use progressively higher levels of theory to optimize this geometry.

However, this is not always the case. For example, it is possible that the user has a very good geometry for the molecule already (for example, perhaps they have already performed a calculation for this species using a good DFT functional, but want to compare with another method). In this case, the user does not want to waste any computational time by starting from the very beginning.

ARC is fairly accommodating for this. For example, you can tell ARC not to perform conformer searches. One thing that ARC does not currently let you do though is bypass an initial optimization step before performing a fine optimization. *Ideally, the user should be able to tell ARC to go directly to the fine optimization in the event that they think the geometry supplied is very close.*

**Describe the solution you'd like**
I would like to add a keyword to ARC's input file called `fine_only` that if `True` will only perform a fine optimization.

**Additional context**
I am planning on implementing this myself, but I would appreciate any guidance as to which parts of ARC will likely need changing, as well as any comments about how this feature should best be implemented to best align with the vision for ARC going forward (if it is a feature that should be implemented in the first place).

**Comment by alongd** [comment]
Thanks! I agree this is necessary.
@dranasinghe once suggested we make it completely modular, so users can specify the exact job types they'd like and the order they'd like to have it executed in.

We already have the `job_types` argument, I think we should make its functionality such that the following specs will do what this issue requests:
```python
job_types =  {
    'conformers': False,
    'opt': False,
    'fine_grid': True,
    'freq': True,
    'rotors': True,
    'sp': True
    'orbitals': False,
},
```

And if we'd like to go really fancy, we could also expand `specific_job_type` to encode the above dict, see something similar [here](https://github.com/ReactionMechanismGenerator/ARC/blob/f89f6f6e75901379097e8b8aa8b3163d9eab3708/arc/common.py#L63).

I **think** the only required change to achieve the original goal requires only slight modification in [scheduler.run_opt_job](https://github.com/ReactionMechanismGenerator/ARC/blob/ececd8f6807a57735117e7099d8b94ee93ae2fcd/arc/scheduler.py#L899)
Perhaps do something like:
```python
fine = self.job_types['fine'] and not self.job_types['opt']
```
and add `fine=fine` to the `self.run_job()` call

**Comment by amarkpayne** [comment]
Sorry I just missed this post before I opened the PR. I can implement something like what you are describing here, where `fine=True, opt=False`  only runs one optimization at a fine level and `fine=True, opt=True` does the default behavior.

As for the future going forward, I agree with you and @dranasinghe that it would be a good idea to make it completely modular so that the user can decide which jobs to run in what order. Perhaps there is a way to balance this so that common or recommended approaches are called by default (or easily) if the user doesn't specify an order explicitly.
