### ISSUE TITLE
ModuleNotFoundError: No module namde 'qcelemental'

### ISSUE THREAD

**Issue by jeehyunatrmg** [ReactionMechanismGenerator/ARC#312]
ARC has been updated to the latest version.

When trying to run ARC under arc environment, cannot import qcelemetnal.

**Comment by amarkpayne** [comment]
This module was added recently. You'll need to update your environment by running the following **while in the ARC environment and from the ARC folder**

`conda env update -f environment.yml`

**Comment by jeehyunatrmg** [comment]
Looks like qcelemental has been solved, but now ARC cannot import the module named 'arkane.ess'

**Comment by amarkpayne** [comment]
Most likely cause is that RMG-Py is not on your PYTHONPATH variable

**Comment by jeehyunatrmg** [comment]
I looked at the bashrc and could found 

export PYTHONPATH=~/RMG-Py/:$PYTHONPATH
export PATH=~/RMG-Py/:$PATH

which means, PYTHONPATH variable might not be the reason

**Comment by jeehyunatrmg** [comment]
problem solved! I was on the old version of RMG-Py! Thanks Mark!
