### ISSUE TITLE
mol_from_xyz cannot handle empty mol_b from molecule_from_xyz

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/ARC#340]
**Describe the bug**
I got the following error (when restarting an ARC job, but this seems unrelated).

```
Traceback (most recent call last):
  File "../../ARC.py", line 73, in <module>
    main()
  File "../../ARC.py", line 66, in main
    arc_object = ARC(input_dict=input_dict, project_directory=project_directory)
  File "/home/ampayne/RMG/ARC/arc/main.py", line 321, in __init__
    self.from_dict(input_dict=input_dict, project=project, project_directory=self.project_directory)
  File "/home/ampayne/RMG/ARC/arc/main.py", line 520, in from_dict
    self.arc_species_list = [ARCSpecies(species_dict=spc_dict) for spc_dict in input_dict['species']]
  File "/home/ampayne/RMG/ARC/arc/main.py", line 520, in <listcomp>
    self.arc_species_list = [ARCSpecies(species_dict=spc_dict) for spc_dict in input_dict['species']]
  File "/home/ampayne/RMG/ARC/arc/species/species.py", line 315, in __init__
    self.from_dict(species_dict=species_dict)
  File "/home/ampayne/RMG/ARC/arc/species/species.py", line 706, in from_dict
    self.mol_from_xyz()
  File "/home/ampayne/RMG/ARC/arc/species/species.py", line 1264, in mol_from_xyz
    if len(mol_b.atoms) == self.number_of_atoms:
AttributeError: 'NoneType' object has no attribute 'atoms'
```

This relates to the code found here:

https://github.com/ReactionMechanismGenerator/ARC/blob/2cf684efd22c85b21fef7e0329f22dba8688a7e4/arc/species/species.py#L1271-L1276

Based on the docstrings, `molecule_from_xyz` can return `None` if perceiving the bond orders did not work. However, we did not check for this possibility in `mol_from_xyz`

In my specific case, checking for `mol_b` and falling back to `mol_s` seemed to have worked (or at least did not throw an error). Is this all that needs to be done?

**Comment by alongd** [comment]
Yes.
A commit in #320 fixes that, but it is good to merge it in befor that PR which will take a while.
Take a look at 0356386a89b875d7b4ba75e7e57c6116d4ad8f17 if you'd like, I think only 3 of the 4 line changes there are relevant.

**Comment by amarkpayne** [comment]
I made one comment on the commit but otherwise it all looks good. Do you want to go ahead and PR this change or would you prefer to wait until PR320 get merged? If you make a PR I don't mind reviewing/merging.

**Comment by alongd** [comment]
Let's go ahead with this fix (either you or me), it shouldn't wait for PR320
