### ISSUE TITLE
Job scheduling improvements for large submissions of species in one ARC job

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/ARC#342]
**Is your feature request related to a problem? Please describe.**
As it stands, ARC can of course submit multiple species at once, troubleshoot their errors independently, and does not crash simply because a single species did not converge. This is extremely valuable, but there are still some improvements that need to be made for ARC to be able to robustly submit hundreds of species at a time. Specifically, the following items need to be addressed:

1. If ARC encounters an exception within ARC itself, this error will bring down the whole job.
2. ARC wait until the very end to submit the Arkane jobs for all of the species, even if some of the species are ready to go and ARC is otherwise idle. This point is especially import given point#1

**Describe the solution you'd like**
I am envisioning the following solutions to the above problems:

1. Inside the main loop of the scheduler, implement an exception handling system (most likely with a try/except statement) that determines which species the exception encountered on, mark the species as failed to converge and cancel its jobs, and then log the exception for later debugging. The ARC job should then continue on with the remaining species.

2. Inside the main loop of scheduler, if ARC detects that a species has successfully converged, it should go ahead and process the species before continuing on with the main scheduler loop.

**Notes**
I am opening this issue primarily to serve as a place to document my finding/proposals for how to implement this in code before opening a PR with these changes if they are agreeable.

**Comment by alongd** [comment]
Let's have a list of species ready to be processed by the statmech adapter. During the Scheduler loop, we'll continue executing jobs, and will process when ARC is idle or if x (default=30?) minutes have passed.

I have an envisioned scheme for a new scheduler, let's merge this into it (i.e. don't open a PR just for that, so we won't have to re-implement it)

**Comment by alongd** [comment]
Transferred to #363
