### ISSUE TITLE
Ignore RMG atomtype and similar errors when using ARC

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/ARC#348]
**Is your feature request related to a problem? Please describe.**
If you try to run ARC on species with unsupported elements/atom type in RMG, the ARC job crashes. While preventing these species in RMG-Py is a good thing, it is not desirable for ARC to throw these exceptions. After all, we would like to use ARC to calculate thermochemistry for these species so that we can expand RMG-Py into uncharted territory. 

**Describe the solution you'd like**
We just merged in a [recent PR by Colin](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1470) that gives an option for ignoring atom type errors when creating molecules and species using RMG's API.  I would like to update ARC so that ALL molecules and species created in ARC ignore these errors. This would have to be something we are mindful of going forward--we'll have to always add these flags whenever we write new code for ARC that deals with creating molecules and species.

**Describe alternatives you've considered**
I have not considered any alternatives, but I would like to check that this approach is okay before proceeding forward. If there is a better solution I am more than happy to implement it instead.

**Comment by alongd** [comment]
I added the recent "don't raise atom type error" key as `True` everywhere in ARC that it was relevant. What was the error you got?
