### ISSUE TITLE
   mpl.use('Agg', warn=False, force=False) TypeError: use() got an unexpected keyword argument 'warn'

### ISSUE THREAD

**Issue by Prajwal3197** [ReactionMechanismGenerator/ARC#437]
I have been trying to install rmg using binary installation but the above error keeps popping up

**Comment by alongd** [comment]
Try installing the developer version of RMG, ARC does not work well with the binaries of RMG. Both repos are dynamic, it's always recommended to use the latest master branches of each. See https://reactionmechanismgenerator.github.io/ARC/installation.html#install-dependencies
