### ISSUE TITLE
Modifying a Gaussian submit script for a PBS server in ARC

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/ARC#467]
Hi Sir/Madam,

I want to set the submit.py needed by ARC run. However, I really have no idea what the directory in the default settings means. As shown below:

```
export g16root=/hpctmp/e0444166/Gaussian16
export PATH=$g16root/g16/:$g16root/gv:$PATH
which g16

###. $g16root/g16/bsd/g16.profile

export GAUSS_SCRDIR=/hpctmp/e0444166/scratch/$PBS_JOB_NAME-$PBS_JOB_ID
mkdir -p $GAUSS_SCRDIR
chmod 750 $GAUSS_SCRDIR
```

 I want to know how can I put the right setting here. FYI, the gaussian is already installed on the remote server.

**Comment by alongd** [comment]
Hi, you should take a typical Gaussian submit script that works for your server, and place it in the appropriate location in submit.py (e.g., under the `servers` -> `server_name` dictionary). You should then look for dynamic variables ARC expects to find in submit scripts (e.g., `{memory}', `{job_type_1}` etc) and use them appropriately.

If the lines above that you specified were taken from a working script on your server (for your user) then you are probably fine leaving them as-is. If you still have questions, please upload a working submit script and I can try to help modifying it.

**Comment by NUSCondy** [comment]
Hi @alongd ，
I check the info about Gaussian on the HPC official site, it shows this:
**All Gaussian 16 jobs shall be submitted through PBS Pro job scheduler to the batch queues. You can submit serial, shared memory parallel and Linda parallel jobs to different queues. You need not to specify the path for scratch folders/files in your input file, the scratch folders/files will be generated in /hpctmp2/g16scratch for each Gaussian job.**
Does it mean that I don't have to install the software and specify the scratch file path, the directly run it?

**Comment by alongd** [comment]
It means you don't need to specify paths to scratch files/folders.
No, you don't need to install Gaussian, your server should already have it. You need to just make sure you can submit Gaussian jobs to the server.
Before using ARC, make you you can manually submit a Gaussian job. Then used that submit file to modify ARC's submit.py.

**Comment by NUSCondy** [comment]
Thank you for your explanation. I can submit jobs using gaussian. I just wondered if I don't include the default cammands, that will affect ARC run. If no need to do that, it will be okay.
