### ISSUE TITLE
Got KeyError: 'molpro' when running an ARC example

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/ARC#468]
Dear Sir,

I am running ARC examples. However, there are still some problems.

1. Error trace
**Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 65, in main
    arc_object.execute()
  File "/home/svu/e0444166/ARC/arc/main.py", line 558, in execute
    fine_only=self.fine_only,
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 457, in __init__
    self.run_sp_job(species.label)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1149, in run_sp_job
    job_type='sp',
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 813, in run_job
    irc_direction=irc_direction,
  File "/home/svu/e0444166/ARC/arc/job/job.py", line 319, in __init__
    self.server = server or self.ess_settings[self.software][0]
KeyError: 'molpro'**

I only got Gaussian and Orca, so I already delete 'Molpro' in my ess settings. Does this mean ARC still want to use Molpro? I wonder how can I solve this problem?

2. Error trace
**Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 64, in main
    arc_object = ARC(**input_dict)
TypeError: __init__() got an unexpected keyword argument 'use_bac'**

It seems that the use_bac in input.yml can not be read by ARC. However, it is not the only example using this. How can I solve this and still set use_bac to False?

Looking forward to your reply!

**Comment by alongd** [comment]
Please upload your input file. Is it possible you did not specify levels of theory? If so, ARC uses its defaults, some of which require Molpro. ARC in general does not require Molpro.

**Comment by NUSCondy** [comment]
Hi @alongd ,
I didn't specify levels of theory so it used the default setting. It seems that when it calculated energy, it is Molpro by default to be called. So it caused the problem. So now if I just want to use gaussian or orca, do I have to change the source codes or specify the software?
FYI. the output file of error info is attache
[rates_demo.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7244242/rates_demo.txt)
d.

**Comment by alongd** [comment]
**You should specify the levels of theory you want to work with.** ARC will determine the correct software to use by the level you specify and the software availability on the server.

**Comment by NUSCondy** [comment]
Hi @alongd ,
I have attached the output file for Molpro error. The original one did not contain the exact settings used.

**Using the following levels of theory:

Conformers: (default) wb97xd/def2svp, software: gaussian (dft)
Geometry optimization: (default) wb97xd/def2tzvp, software: gaussian (dft)
Frequencies: (user-defined opt) wb97xd/def2tzvp, software: gaussian (dft)
Energy: (default) ccsd(t)-f12/cc-pvtz-f12, software: molpro (wavefunction)
Rotor scans: (user-defined opt) wb97xd/def2tzvp, software: gaussian (dft)
IRC: (default) wb97xd/def2tzvp, software: gaussian (dft)**

It seems that energy is calculated by Molpro. How do I avoid it using Molpro to calculate energy? Also, there is no Molpro available on my server.
[thermo_demo.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7248413/thermo_demo.txt)
.

**Comment by alongd** [comment]
Hi, you should specify the levels of theory you want to work with. Otherwise, ARC uses `CCSD(T)-F12` for single-point energy by default, and naturally looks for Molpro.
You can do this by specifying in your ARC input file something like:

```yaml
level_of_theory: wb97xd/def2tzvp
```

or more specific, if you choose:
```yaml
opt_level: wb97xd/def2tzvp
freq_level: ... your level here ...
sp_level: ... your level here ...
rotors_level: ... your level here ...
```

Of course, change "... your level here ..." to the actual level of theory (DFT? higher?) that you'd like to use in Gaussian.

**Comment by NUSCondy** [comment]
Hi @alongd,
Noted with many thanks!

**Comment by alongd** [comment]
Great, I hope it works smooth, let me know if you experience any additional issue. Good luck!

**Comment by NUSCondy** [comment]
Hi @alongd,

If I set the level myself, then the software could be chosen. However, then another error of arkane show up:
**### Using the following levels of theory:

Conformers: (default) wb97xd/def2svp, software: gaussian (dft)
TS guesses: (default) wb97xd/def2svp, software: gaussian (dft)
Geometry optimization: (default) wb97xd/def2tzvp, software: gaussian (dft)
Frequencies: (user-defined opt) wb97xd/def2tzvp, software: gaussian (dft)
Energy: (default) ccsd(t)-f12/cc-pvtz-f12 (wavefunction)
Warning: Not performing rotor scans, since it was not requested by the user. This might compromise finding the best conformer, as dihedral angles won't be corrected. Also, the calculated thermodynamic properties and rate coefficients will be less accurate.
IRC: (default) wb97xd/def2tzvp, software: gaussian (dft)
Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/arc/level.py", line 392, in to_arkane_level_of_theory
    arkane_data.atom_energies[var_1]
KeyError: LevelOfTheory(method='ccsd(t)f12',basis='ccpvtzf12')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/arc/level.py", line 396, in to_arkane_level_of_theory
    arkane_data.atom_energies[var_2]
KeyError: LevelOfTheory(method='ccsd(t)f12',basis='ccpvtzf12')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 64, in main
    arc_object = ARC(**input_dict)
  File "/home/svu/e0444166/ARC/arc/main.py", line 405, in __init__
    self.check_arkane_level_of_theory()
  File "/home/svu/e0444166/ARC/arc/main.py", line 1081, in check_arkane_level_of_theory
    self.arkane_level_of_theory.to_arkane_level_of_theory(variant='AEC', raise_error=self.compute_thermo)
  File "/home/svu/e0444166/ARC/arc/level.py", line 400, in to_arkane_level_of_theory
    raise ValueError(f'Missing Arkane atom energy corrections for {var_1}\n'
ValueError: Missing Arkane atom energy corrections for LevelOfTheory(method='ccsd(t)f12',basis='ccpvtzf12')
(If you did not mean to compute thermo, set the compute_thermo argument to False to avoid this error.)**
 
As it is a thermo_demo, I think I can not set computer_thermo to False, right? I also try to set the method and basis to the default, it shows the same. How could this be avoided since it is not the first time I encountered it.

**Comment by alongd** [comment]
If you want to compute accurate thermodynamic properties, you'll need energy corrections. We only support those available in Arkane (see the table [here](https://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#model-chemistry)).

Also, you'll need to have frequency scaling factors from Arkane, see https://github.com/ReactionMechanismGenerator/ARC/issues/197

Since you're only running a thermo demo, you can set:

```yaml
bac_type : none
freq_scale_factor: 1.0
```

To just make it run without energy corrections and freq scaling factor.

After the demo runs successfully, if you'd like to get accurate thermo, use only levels supported by Arkane (or make your own energy corrections and add them to Arkane).
If you're trying to compute reaction rate coefficients, then you don't need energy corrections.

**Comment by NUSCondy** [comment]
Hi @alongd,

I have checked the method and basis that is supported by Arkane, it seems that all the level I set is in the list. However, when they are transferred from leveloftheory to arkaneleveloftheory, the format cannot be read anymore? Can I understand it like this? If so, can I avoid make such mistakes by setting arkaneleveloftheory separately?

However, even I set compute_thermo to False, the scan calculation also crack down, as shown below:
  **Running job scan_a235 for vinoxy (pivots: [4, 1, 2, 3], dihedrals: ['4.00', '1.00', '2.00', '3.00'])
/home/svu/e0444166/ARC/arc/plotter.py:907: UserWarning: FixedFormatter should only be used together with FixedLocator
  axs.set_yticklabels(['' for _ in range(len(torsions))])
/home/svu/e0444166/ARC/arc/plotter.py:907: UserWarning: FixedFormatter should only be used together with FixedLocator
  axs.set_yticklabels(['' for _ in range(len(torsions))])
/home/svu/e0444166/ARC/arc/plotter.py:907: UserWarning: FixedFormatter should only be used together with FixedLocator
  axs.set_yticklabels(['' for _ in range(len(torsions))])
/home/svu/e0444166/ARC/arc/plotter.py:907: UserWarning: FixedFormatter should only be used together with FixedLocator
  axs.set_yticklabels(['' for _ in range(len(torsions))])
Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 65, in main
    arc_object.execute()
  File "/home/svu/e0444166/ARC/arc/main.py", line 558, in execute
    fine_only=self.fine_only,
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 471, in __init__
    self.schedule_jobs()
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 542, in schedule_jobs
    self.spawn_post_opt_jobs(label=label, job_name=job_name)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1365, in spawn_post_opt_jobs
    self.run_scan_jobs(label)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1212, in run_scan_jobs
    self.spawn_directed_scan_jobs(label, rotor_index=i)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1434, in spawn_directed_scan_jobs
    pivots=pivots)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 823, in run_job
    self.job_dict[label][job_type][job.job_name].run()
  File "/home/svu/e0444166/ARC/arc/job/job.py", line 1313, in run
    self.write_input_file()
  File "/home/svu/e0444166/ARC/arc/job/job.py", line 999, in write_input_file
    scans.append(' '.join([str(num) for num in directed_scan]))
TypeError: 'int' object is not iterable**

This seems like a codes error rather than an input error right?

**Comment by alongd** [comment]
Please upload your input file, seems like your spawning directed_rotors

**Comment by NUSCondy** [comment]
Sure.
