### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/ARC#469]
Dear Sir,

I am running ARC using input.yml and start from examples. However, several times I am encountered the problem of 'Unexpected keyword argument'. As shown below:
**Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 64, in main
    arc_object = ARC(**input_dict)
TypeError: __init__() got an unexpected keyword argument 'scan_rotors'**

FYI, it is not the only unexpected one, some advanced features like 'initial_trsh', 'use_bac' indicated on ARC tutorials are also unexpected inputs. I wonder is it because they are all inputs for the original ARC version that are not working for ARC 1.1.0? Since I check the import of main.py, indeed these are not the expected inputs.

Looking forward to your reply!

**Comment by alongd** [comment]
Hi, you can see the API to the `ARC` class here: https://reactionmechanismgenerator.github.io/ARC/api/main.html#arc.main.ARC

Note that `input_dict` is indeed not a valid argument.
If `input_dict` is a Python dictionary with valid ARC arguments as keys, try passing it like this:
```python
arc_object = ARC(**input_dict)
```
