### ISSUE TITLE
Level of theory cannot be read by Arkane

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/ARC#472]
Hi @alongd ,
As taught by you, I only pass the model chemistry that is supported by Arkane to the level of theory. When I pass 'CBS-QB3' it works. However, when I pass 'CCSD-F12/cc-pVDZ-F12', it seems it doesn't work. Is it because it cannot read '/' in that?
[COC2input.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7256698/COC2input.txt)
[COC2error.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7256699/COC2error.txt)

**Comment by alongd** [comment]
Before I get to the technical answer, I'm just making sure that you know it isn't recommended to use `CCSD-F12/cc-pVDZ-F1` energy correction with a CBS-QB3 computation. I guess you are playing around with the options to see that it works?

`arkane_level_of_theory` is indeed a nice "trick" to fool Arkane and get the energy corrections you want, even if slightly not exactly computed for the level you are actually using.

Please try the following, let me know if it worked:

```yaml
arkane_level_of_theory:
  method: CCSD-F12
  basis: cc-PVDZ-F12
```

**Comment by NUSCondy** [comment]
Hi @alongd ,
Yes, I just want to try some options in that. But if there are any instructions on how to choose a good energy correction method?

**Comment by alongd** [comment]
The best energy correction method is the exact method (and basis set, and software) that you're using for the `sp` calculations. Everything else is not really recommended for publication-grade results.

**Comment by NUSCondy** [comment]
Hi @alongd,
It seems that Arkane still does not accept the level of theory I specified. And keep reporting:
 **ValueError: Missing Arkane atom energy corrections for LevelOfTheory(method='ccsdf12',basis='ccpvdzf12')**
Is that anyway I can input the level of theory to Arkane? Or normally, which LOT do you recommend or use?

**Comment by alongd** [comment]
Looking at the database, Arkane supports `LevelOfTheory(method='ccsdf12',basis='ccpvdzf12',software='molpro')` (see [here](https://github.com/ReactionMechanismGenerator/RMG-database/blob/main/input/quantum_corrections/data.py#L308))

A technical solution:

```yaml
arkane_level_of_theory:
  method: CCSD-F12
  basis: cc-PVDZ-F12
  software: molpro
```

But this is an artifact since you are feeding a level of theory you're not actually using.

**Comment by NUSCondy** [comment]
I understand why it could not be read now. The method works. Now it becomes the same problem as #471 Also, I attached the input file:
[input.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7271065/input.txt)

**Comment by alongd** [comment]
OK, so I'm closing this issue, we'll solve #471 seperately
