### ISSUE TITLE
Troubleshooting SP job by silently using wb97-x3/def2tzvp

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/ARC#479]
I'm using a fairly modified version of ARC, but I don't think I've tampered with this particular aspect and I think it's a quite dangerous bug. When running CCSD(T)-F12//cc-pvdz-f12 single points that don't converge after enough troubleshooting ARC eventually troubleshoots the single point calculation by using wb97x-d3/def2tzvp. This results in a couple problems, the first is apart from the note in the log that it's running the fact that it does this is entirely silent (the only way I've been able to check this without trying to read the log file is by searching for species that don't have T1 recorded) and the second being that I'm pretty sure it's applying the AECs and BACs for CCSD(T)-F12//cc-pvdz-f12 to the wb97x-d3/def2tzvp calculation resulting in crazy thermochemistries and barriers. I think this troubleshooting method probably made a lot of sense for a opt or scan job, but needs a check to make sure it doesn't do so for an sp job.

**Comment by alongd** [comment]
Excellent point, I agree and will take a look
