### ISSUE TITLE
Scissors for cyclic molecules.

### ISSUE THREAD

**Issue by kfir4444** [ReactionMechanismGenerator/ARC#506]
**Is your feature request related to a problem? Please describe.**
I am currently working on atom mapping, which requires to call the function `scissors` several times. It seems, however, that scissoring of cyclic species doesn't work, and return the error:
`Could not split {self.label} between indices {indices}.`
The reason seems to be that if the scissored species is a cyclic one, and the scission is on the cycle, than scissoring said bond should results in a one linear species and not two, like would be on a linear molecule, while the function `scissors` assume there will be two xyz's and two molecules as the result of the scission. 

**Describe the solution you'd like**
The solution could be either a separating the scissors engine (`_scissors`) into two functions, for linear and cyclic species, with a certain condition between them (for example, the `self.mol.is_cyclic()` function), or a more general solution, that ignores the function's assumptions to an amount of xyz's and molecules.

**Additional context**
```
from arc.species import ARCSpecies
c_c3h6_xyz = {'coords': ((0.7868661913782324, -0.3644249639827158, -0.016337299842911886),
                         (-0.07793785747147405, 0.8603229755261934, 0.07746513362297117),
                         (-0.708928275400647, -0.4958980792223481, -0.06112784358024908),
                         (1.339749295484817, -0.5278616711993785, -0.9341881111902739),
                         (1.3001119953298585, -0.6947493102195698, 0.8793780279658545),
                         (-0.15055582331881673, 1.3597070015370083, 1.0367271647162946),
                         (-0.11091839380255, 1.5265948517709569, -0.7768389650606503),
                         (-1.1693748373792934, -0.7484015319217499, -1.0093221066790388),
                         (-1.2090122948201234, -0.9152892722884018, 0.8042440000480116)),
              'isotopes': (12, 12, 12, 1, 1, 1, 1, 1, 1), 'symbols': ('C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H')}

p_1 = ARCSpecies(label='cC3H6', smiles='C1CC1', xyz=c_c3h6_xyz)
p_1.bdes = [(1,3)]
p_1.final_xyz = p_1.get_xyz()
linear_spc = p_1.scissors()
```
This returns `[]` with `WARNING:arc:Could not split cC3H6 between indices (0, 2).`
instead of the linear species.

**Comment by alongd** [comment]
closed by #508
