### ISSUE TITLE
Conda env create takes too long

### ISSUE THREAD

**Issue by anandijain** [ReactionMechanismGenerator/ARC#510]
The developer installation of RMG-Py doesn't work for me, it just tries to do environment resolution for hours. Similarly for `conda env create -f environment.yml` with ARC. I don't use python much, how long is reasonable to wait? should I let it run for hours?

Anyways my alternative was to try the binary RMG-Py, since it looks like the latest binary version of RMG-Py has Arkane, so I wanted to see if maybe it would work if I manually created the env and `conda install`ed everything to avoid `solving environment`. It looked like it was about to work 
```
Starting project reaction_demo


Traceback (most recent call last):
  File "ARC.py", line 69, in <module>
    main()
  File "ARC.py", line 64, in main
    arc_object = ARC(**input_dict)
  File "/home/anandijain/rmg2/ARC/arc/main.py", line 340, in __init__
    converted_species.append(ARCSpecies(species_dict=spc))
  File "/home/anandijain/rmg2/ARC/arc/species/species.py", line 508, in __init__
    self.set_mol_list()
  File "/home/anandijain/rmg2/ARC/arc/species/species.py", line 926, in set_mol_list
    save_order=True,
  File "rmgpy/molecule/molecule.py", line 2108, in rmgpy.molecule.molecule.Molecule.generate_resonance_structures
TypeError: generate_resonance_structures() got an unexpected keyword argument 'save_order'
```
but sadly, I'm guessing this kwarg is a thing from source, not yet in binaries. I just want to try ARC, is there any way to actually use this package?

Thanks for the package, I'm looking forward to using it, I'm just a bit frustrated with conda I think.

**Comment by alongd** [comment]
That's correct, ARC requires the latest RMG dev version (not binaries)

We can recommend installing the environment using `mamba` insread of `conda`

Try installing [mamba](https://anaconda.org/conda-forge/mamba):
```
conda install -c conda-forge mamba
```

Then install the envs by:
```
mamba env create -f environment.yml
```

**Comment by alongd** [comment]
@anandijain, let us know if you're still experiencing issues. I'll close this ticket for now, feel free to reopen it if needed.
