### ISSUE TITLE
Error with syntax

### ISSUE THREAD

**Issue by naddeu** [ReactionMechanismGenerator/ARC#576]
Hello, 
when running ARC with basis set "def2-tzvp" received an error:
`Warning: Troubleshooting h job opt_a15284 which failed with status: "errored,"
with keywords: ['Syntax'] in gaussian. 
Troubleshooting opt job in gaussian for h using int=(Acc2E=14)`
and Gaussian started using cbs-qb3 for the optimization job

This is the input.yml file I used
`#AutoTST
project: ax_1010

level_of_theory: B3LYP/6-31G(d,p)//apfd/def2-tzvp

species:
  - label: a
    smiles: C[CH]O
    
  - label: a1
    smiles: '[CH2]CO'

  - label: b
    smiles: C[O]

  - label: b1
    smiles: '[CH2]O'

  - label: c
    smiles: '[CH2]CCO'

  - label: c1
    smiles: C[CH]CO

  - label: d
    smiles: '[CH2]CCC'

  - label: d1
    smiles: CC[CH]C
    
  - label: e
    smiles: CCCC([O])=O
    
  - label: e1
    smiles: '[CH2]CCC(=O)O'

  - label: f
    smiles: CC(=O)O[O]

  - label: f1
    smiles: '[CH2]C(=O)OO'

  - label: g
    smiles: C[CH]C1C=CC=C1

  - label: g1
    smiles: '[CH2]CC1C=CC=C1'

  - label: h
    smiles: '[CH]1C=CC=CCC1'

  - label: h1
    smiles: '[CH]1CC=CC=CC1'
      
  - label: i
    smiles: C=CC1[CH]CC=C1
    
  - label: i1
    smiles: C=C[C]1C=CCC1

  - label: j
    smiles: C=C1[CH]C(C)C=C1

  - label: j1
    smiles: '[CH2]C1C=CC(=C)C1'

reactions:
  - label: a <=> a1
  
  - label: b <=> b1

  - label: c <=> c1
  
  - label: d <=> d1
  
  - label: e <=> e1
  
  - label: f <=> f1

  - label: g <=> g1
  
  - label: h <=> h1
  
  - label: i <=> i1

  - label: j <=> j1

`
I hoped to receive valid reaction rates with optimized TS geometries

**Comment by kfir4444** [comment]
Dear @naddeu,
Thanks for reporting this issue, it is now solved with [this PR](https://github.com/ReactionMechanismGenerator/ARC/pull/577),
When you are able, pull and rerun and let me know if it's still not working.
